[package]
name = "comfy-table"
description = "An easy to use library for building beautiful tables with automatic content wrapping"
version = "4.1.1-alpha.0"
authors = ["Arne Beer <contact@arne.beer>"]
homepage = "https://github.com/nukesor/comfy-table"
repository = "https://github.com/nukesor/comfy-table"
documentation = "https://docs.rs/comfy-table/"
license = "MIT"
keywords = ["shell", "commandline", "table", "unicode"]
readme = "README.md"
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
crossterm = "0.20"
strum = "0.21"
strum_macros = "0.21"
unicode-width = "0.1"

[dev-dependencies]
pretty_assertions = "0.7"
doc-comment = "0.3"
proptest = "1"
criterion = "0.3"

[[bench]]
name = "build_tables"
harness = false
