ignore:
  - "benches"
  - "examples"
  - "proptest_regressions"
  - "tests"
  - "README.md"
  - "LICENSE"
  - "Cargo.lock"
  - "Cargo.toml"

codecov:
  status:
    project:
      default:
        target: auto
        threshold: 5%
